services:
  location-service: 
    platform: linux/amd64
    build: 
      context: ../../Chapter5/location-service/
    image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/developer-guide-to-compose-ecr:location-service_0.1 
    environment: 
      - REDIS_HOST=redis:6379 
    depends_on: 
      - redis 
    networks: 
      - location-network 
      - redis-network 
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"] 
      interval: 10s 
      timeout: 5s 
      retries: 5 
      start_period: 5s 
  redis: 
    image: redis 
    networks:
      - redis-network
  event-service: 
    platform: linux/amd64    
    build: 
      context: ../../Chapter5/events-service/
    image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/developer-guide-to-compose-ecr:events-service_0.1 
    environment: 
      - REDIS_HOST=redis:6379 
    depends_on: 
      - redis 
    networks: 
      - redis-network 
  task-manager: 
    platform: linux/amd64
    build: 
      context: ../../Chapter5/task-manager/
    image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/developer-guide-to-compose-ecr:task-manager_0.1
    ports: 
      - 8080:8080 
    environment: 
      - REDIS_HOST=redis:6379 
      - LOCATION_HOST=http://location-service:8080
    depends_on: 
      - redis 
      - location-service
    networks: 
      - location-network 
      - redis-network 
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"] 
      interval: 10s 
      timeout: 5s 
      retries: 5 
      start_period: 5s 
networks:
  location-network:
  redis-network:
