x-aws-vpc: "vpc-0144f03210f0da8e5"
x-aws-cluster: "guide-to-compose-ecs"
x-aws-loadbalancer: "guide-to-compose-load-balancer"

services:
  event-service: 
    platform: linux/amd64    
    build: 
      context: ../Chapter5/events-service/
    image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/developer-guide-to-compose-ecr:events-service_0.1 
    environment: 
      - REDIS_HOST=redis:6379 
    depends_on: 
      - redis 
    networks: 
      - redis-network 
    logging:
      options:
        awslogs-group: "/ecs/task-api"
    deploy: 
      mode: replicated 
      replicas: 2 
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first   
  location-service: 
    platform: linux/amd64
    build: 
      context: ../Chapter5/location-service/
    image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/developer-guide-to-compose-ecr:location-service_0.1 
    environment: 
      - REDIS_HOST=redis:6379 
    depends_on: 
      - redis 
    networks: 
      - location-network 
      - redis-network 
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"] 
      interval: 10s 
      timeout: 5s 
      retries: 5 
      start_period: 5s 
    logging:
      options:
        awslogs-group: "/ecs/task-api"
    deploy: 
      mode: replicated 
      replicas: 2 
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first 
  redis: 
    image: redis 
    networks:
      - redis-network
    logging:
      options:
        awslogs-group: "/ecs/task-api"
  task-manager: 
    platform: linux/amd64
    build: 
      context: ../Chapter5/task-manager/
    image: 111111111111.dkr.ecr.eu-west-1.amazonaws.com/developer-guide-to-compose-ecr:task-manager_0.1
    ports:
      - 80:80
    environment: 
      - REDIS_HOST=redis:6379 
      - LOCATION_HOST=http://location-service:8080
      - TASK_MANAGER_HOST=:80
    depends_on: 
      - redis 
      - location-service
    networks: 
      - location-network 
      - redis-network 
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"] 
      interval: 10s 
      timeout: 5s 
      retries: 5 
      start_period: 5s 
    logging:
      options:
        awslogs-group: "/ecs/task-api"
    deploy: 
      mode: replicated 
      replicas: 2 
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      x-aws-autoscaling:
        min: 1
        max: 3
        cpu: 75 
    secrets:
      - secret-file   
    command:
      - /bin/sh
      - -c
      - |
        cat /run/secrets/secret-file
        ls
        /task_manager
networks:
  location-network:
  redis-network:
secrets:
  secret-file:
    file: ./secret.file.txt
